fix: MissingAllowedListProof: Missing allowed list proof
error log

---
% ts-node mintWithGuardsAllowList.ts
MissingAllowedListProof: Missing allowed list proof

Source: Program > mplCandyGuard [Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g]

Caused By: Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x178b

Program Logs:
| Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1]
| Program log: Instruction: MintV2
| Program log: AnchorError thrown in program/src/guards/allow_list.rs:205. Error Code: MissingAllowedListProof. Error Number: 6027. Error Message: Missing allowed list proof.
| Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 31609 of 200000 compute units
| Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g failed: custom program error: 0x178b

    at getMplCandyGuardErrorFromCode (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/mpl-candy-machine/src/generated/errors/mplCandyGuard.ts:744:24)
    at Object.getErrorFromCode (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/mpl-candy-machine/src/generated/programs/mplCandyGuard.ts:28:43)
    at Object.resolveError (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/umi-program-repository/src/createDefaultProgramRepository.ts:135:35)
    at Object.sendTransaction (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/umi-rpc-web3js/src/createWeb3JsRpc.ts:335:42)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async TransactionBuilder.sendAndConfirm (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/umi/src/TransactionBuilder.ts:359:23) {
  source: 'program',
  sourceDetails: 'mplCandyGuard [Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g]',
  cause: SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x178b
      at Connection.sendEncodedTransaction (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@solana/web3.js/src/connection.ts:5922:13)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Connection.sendRawTransaction (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@solana/web3.js/src/connection.ts:5881:20)
      at async Object.sendTransaction (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/umi-rpc-web3js/src/createWeb3JsRpc.ts:327:25)
      at async TransactionBuilder.sendAndConfirm (/Users/user/Documents/Programming/Blockchain/solana-anchor-react-minimal-example/scripts/metaplex/candy-machine_v6.0_umi_v0.8/node_modules/@metaplex-foundation/umi/src/TransactionBuilder.ts:359:23) {
    logs: [
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1]',
      'Program log: Instruction: MintV2',
      'Program log: AnchorError thrown in program/src/guards/allow_list.rs:205. Error Code: MissingAllowedListProof. Error Number: 6027. Error Message: Missing allowed list proof.',
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 31609 of 200000 compute units',
      'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g failed: custom program error: 0x178b'
    ]
  },
  program: {
    name: 'mplCandyGuard',
    publicKey: 'Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g',
    getErrorFromCode: [Function: getErrorFromCode],
    getErrorFromName: [Function: getErrorFromName],
    isOnCluster: [Function: isOnCluster],
    availableGuards: [
      'botTax',           'solPayment',
      'tokenPayment',     'startDate',
      'thirdPartySigner', 'tokenGate',
      'gatekeeper',       'endDate',
      'allowList',        'mintLimit',
      'nftPayment',       'redeemedAmount',
      'addressGate',      'nftGate',
      'nftBurn',          'tokenBurn',
      'freezeSolPayment', 'freezeTokenPayment',
      'programGate',      'allocation',
      'token2022Payment'
    ]
  },
  logs: [
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g invoke [1]',
    'Program log: Instruction: MintV2',
    'Program log: AnchorError thrown in program/src/guards/allow_list.rs:205. Error Code: MissingAllowedListProof. Error Number: 6027. Error Message: Missing allowed list proof.',
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g consumed 31609 of 200000 compute units',
    'Program Guard1JwRhJkVH6XZhzoYxeBVQe872VH6QggF4BWmS9g failed: custom program error: 0x178b'
  ],
  code: 6027
}